### ISSUE TITLE
Enable powering non-playnite-web-app experiences by providing API to retrieve data

### ISSUE THREAD

**Issue by andrew-codes** [andrew-codes/playnite-web#318]
Currently, the API to access games is baked into playnite-web-app. The goal is to provide an API that both playnite-web and others can consume. This will enable others to create their own end-user experiences to interact with playnite-web as a whole.

## Game Queries

- [x] Game by id 
- [x] All games in library
- [x] Games' releases 
- [x] Releases' platforms
- [x] Releases' completion status
- [x] Releases' features
- [x] Other game properties

### Query up the tree

- [x] completion status' games 
- [x] Features' games
- [x] platforms' games
- [x] Games' playlists

**Comment by andrew-codes** [comment]
I'm thinking of including a GraphQL API. Would this empower your use case @cvele?

**Comment by cvele** [comment]
Absolutely! Especially if subscription model was included.

**Comment by andrew-codes** [comment]
@matt-quests-for-tacos , breaking the playlist graph feature into a separate issue. I'll assign to you since we were working on it together.
