### ISSUE TITLE
Cannot read properties of null (reading 'name')

### ISSUE THREAD

**Issue by bfalala** [andrew-codes/playnite-web#482]
Hello, 
Since v5, my library is empty and I get this error log in docker:
![playnite-web-app.csv](https://github.com/user-attachments/files/16610595/playnite-web-app.csv)

**Comment by andrew-codes** [comment]
Hi, thanks for reporting the issue. What version were you running previously that was working or is v5 your first time using Playnite-Web? Also, you mentioned your library is empty. Did you previously have a filled library in the database or are you indicating that it is currently empty when this error message was produced?

**Comment by bfalala** [comment]
Hi,
I was running the last v4. I had 2700+ games in my library.
When upgrading to v5 I also decided to start clean with an empty DB because I was using the old mongodb 4.4. I'm now running v6.2. It seems the DB has been filled successfully using playnite web plugin given the size of the DB directory. The error log was produced after that when I tried to access playnite web interface and I expected to see items in it at this point.

**Comment by andrew-codes** [comment]
Ah ok. Thanks for that insight. Let me investigate further. My initial guess is that there is some piece of data that may be missing or a game/platform/etc. that has an unexpected value. Playnite-Web should handle these cases, but it may be one that I do not have in my own library for my own local testing. Determining the exact data item may be challenging given I do not have your database.

I will add some better logging in the area of the code that appears to have the issue based on your error logs. I will then push this and open a pull request. There will be an image created for that pull request that I would then ask you to use and report back with the new error logs. I will notify once the PR is ready. Thanks for your patience.

**Comment by andrew-codes** [comment]
Ok, so there is a PR, #487 that adds some better debug statements. Please try pulling the latest PR-487 image and run it. Please ensure the `DEBUG` environment variable is set to `playnite*`. Once running, try to again and please report back the logs. I'm hoping to identify which game release is missing some of its data. This will help me track down the why and ultimately come up with a fix. Thank you!

**Comment by 2600box** [comment]
Here are the logs for mongo and the web app with the PR-487 image.

debug is set to `playnite/*`

[db.log](https://github.com/user-attachments/files/16627318/db.log)
[web.log](https://github.com/user-attachments/files/16627320/web.log)

**Comment by andrew-codes** [comment]
Thank you! I do see some data issues. I have just pushed a fix in the same PR image. It will now log out when a game has no source associated to it, so it will be easier to identify and correct in Playnite. It will also not fail and instead show as an unknown platform in this case.

**Comment by 2600box** [comment]
Just to follow-up, 5.0.5 showed about 3/4 of my library, but 5.1.1 shows my full library, so we are all good now
