### ISSUE TITLE
Pipeline should bump version of HASS addon automatically

### ISSUE THREAD

**Issue by cvele** [andrew-codes/playnite-web#557]
HASS can track versions of add-ons and notify users of any updates which are then handled automatically. To get it to work version in this file should be bumped along with others.

Version: https://github.com/andrew-codes/playnite-web/blob/main/hass-playnite-web/config.json#L4

**Comment by andrew-codes** [comment]
For additional information, there is a [target](https://github.com/andrew-codes/playnite-web/blob/f8b85b4b3eaa9ee2c5df1314802a914f1fc5eee8/hass-playnite-web/project.json#L20) that may already bump the version in the config.json. I think it should be happening via this [release configuration](https://github.com/andrew-codes/playnite-web/blob/f8b85b4b3eaa9ee2c5df1314802a914f1fc5eee8/release.config.js#L55). I'm not certain it actually committing the version bump though. 

We want to bump the version and amend the commit prior to tagging the release or releasing. This should all happen had part of the release process, which happens via this [single command](https://github.com/andrew-codes/playnite-web/blob/f8b85b4b3eaa9ee2c5df1314802a914f1fc5eee8/.github/workflows/publish-release.yml#L344).
