### ISSUE TITLE
Wider support of PC game sources

### ISSUE THREAD

**Issue by bfalala** [andrew-codes/playnite-web#559]
Hi,
Since v8, a lot of games are missing. It seems to be related to the source library. For instance, games from Steam are listed but not the ones from my itch.io library.
I provide you with the logs but it seems the reported issues are always about missing assets...
[playnite-web-app.csv](https://github.com/user-attachments/files/17176725/playnite-web-app.csv)

**Comment by andrew-codes** [comment]
Hi. Thanks for opening an issue. At the moment I've only implemented maybe 4 PC game sources and itch.io was not one of them. However, they are very easy to add. What PC sources do you have in total? I want to ensure I get them all in one go. Thanks again.

**Comment by andrew-codes** [comment]
Oh sorry. Just saw the csv file. I'll take a look at it once I'm back in town and cut a release with the new sources included.

**Comment by andrew-codes** [comment]
For reference: the [code location](https://github.com/andrew-codes/playnite-web/blob/fa5ee4d10b5e999da141e43b36dd03d6d2b1da21/apps/PlayniteWebPlugin/src/Models/Game.cs#L36) where sources are mapped/considered to be a PC platform. These are exact match strings OR regular expressions that are matched against Playnite games source's name.

**Comment by bfalala** [comment]
> Hi. Thanks for opening an issue. At the moment I've only implemented maybe 4 PC game sources and itch.io was not one of them. However, they are very easy to add. What PC sources do you have in total? I want to ensure I get them all in one go. Thanks again.

Hi, here are the PC sources I have. I just hid the sources that should not be added (Geforce Now for instance).
![image](https://github.com/user-attachments/assets/c6d0432a-6550-4e92-9c0d-2095d295092d)

**Comment by andrew-codes** [comment]
Note to self: Currently, Xbox PC games are not recognized. This is because there is no way to know if a game associated from a single Xbox source should be considered on an Xbox or PC platform. This will require added thought as to how to best support this.
