### ISSUE TITLE
Better documentation around CSP_ORIGINS values

### ISSUE THREAD

**Issue by mxp83** [andrew-codes/playnite-web#561]
Sorry, I'm very new to writing in Docker, but how do I enter CSP_origin values in a web editor?

Currently I have 
`     - CSP_ORIGINS=`

I'm reading the [app.ts](https://github.com/andrew-codes/playnite-web/commit/9ca30b5006145b7f8effcb1f222174babfcb6b39#diff-6aa5eb8dd43186a64da204b8e192590a5e040b60715c3b085bab54728c504ebd) file but it is written out like:

```
          ].concat(cspOrigins),
          'script-src': ["'self'", "'unsafe-inline'", 'unpkg.com'].concat(
            cspOrigins,
          ),
          'img-src': ["'self'", 'raw.githubusercontent.com'].concat(cspOrigins),
          'font-src': ["'self'", '*.googleapis.com', '*.gstatic.com'].concat(
            cspOrigins,
          ),
```

How do I write it?  With bracket text included?

**Comment by mxp83** [comment]
I've written my compose file section like so, and it doesn't work:

      - CSP_ORIGINS=img-src 'self', img-src 'self' raw.githubusercontent.com, font-src 'self', font-src 'self' *.googleapis.com, font-src 'self' *.gstatic.com, script-src 'self'

**Comment by andrew-codes** [comment]
Hi, thank you for your submission. First, let me provide some information that should help unblock you for now. Secondly, I'll use this issue to track the necessary improvements to the documentation.

`CSP_ORIGINS` is a comma-delimited string of domains and/or subdomains that the site and browser are allowed to reference and load content from. As an example, some games have descriptions that reference external sites to load in added images into the description. Natively, Playnite Web will block loading any content from all external sites for security reasons. `CSP_ORIGINS` is a way to override this behavior and white-list specific site domains/subdomains that are allowed to load content in Playnite Web's UI.

So, for example, if you want to allow content from `images.google.com` and `images.bing.com`, to be loaded in the Playnite Web UI, then you can set `CSP_ORIGINS` to something like the below code snippet:

```sh
- CSP_ORIGINS="images.google.com,images.bing.com"
```

A few things to note in the above snippet:

1. The value is enclosed within double quotes. This ensures it is treated as a string. In the example you provided, there are spaces and not enclosing double quotes. This means only `img-src` is treated as the value and the rest is unable to be parsed.
2. Note there are not spaces, just the exact values separated by a single comma.

What origins are you attempting to add? I noticed in your provided example, that you there are not really any new origins being added.

**Comment by andrew-codes** [comment]
For reference, this issue can track documentation changes to make it more clear what values `CSP_ORIGINS` should accept.

**Comment by mxp83** [comment]
I was getting errors regarding img-src 'self' so I wanted to edit my docker config.  I just needed the formatting and you'e answered.  Thank you.
