### ISSUE TITLE
Stop a release

### ISSUE THREAD

**Issue by andrew-codes** [andrew-codes/playnite-web#574]
Users should be able to stop a game release from Playnite Web. This functionality requires a user to be authenticated.

## UX

- [ ] Users that are not authenticated do not see a start, stop, or restart buttons in the game details pane.
- [ ] Authenticated users can stop a running game from the game's details pane.
- [ ] Stop button is only available when a release of the game is running.

## Graph API

- [ ] Given a game release's ID, platform (name and ID), a game release stop request is performed in the form of an internal MQTT message. This internal MQTT message is picked up by the Playnite Web plugin.
    - [ ] The release is only processed if the release and platform is found in that Playnite instance.
    - [ ] If the release/platform is found and is a computer platform, then the running game's process is killed.
        - Note this may require tracking the process ID in the plugin in some manner.
    - [ ] If the release/platform is found and is not a computer platform, then publish an external MQTT message to stop the game. This message is intended to be consumed by external services. Include the game release's name, ID, game ID, and platform (name, ID)
- [ ] Graph API provides a subscription for the currently playing game's runtime state, including the releases' ID, name, game ID, and process ID (if available).
- [ ] Querying for a game or games can include the runtime state of games.

**Comment by cvele** [comment]
Have you seen Playstate plugin ?

https://github.com/darklinkpower/PlayniteExtensionsCollection/wiki/PlayState

I'm wondering if we could apply similar logic for stopping games.

**Comment by cvele** [comment]
eg.

```

        public static void CloseActiveWindow()
        {
            IntPtr foregroundWindow = GetForegroundWindowHandle();
            if (foregroundWindow != IntPtr.Zero)
            {
                PostMessage(foregroundWindow, WM_CLOSE, IntPtr.Zero, IntPtr.Zero);
            }
        }

        public static void KillProcessAssociatedWithWindow(IntPtr windowHandle)
        {
            uint processId;
            GetWindowThreadProcessId(windowHandle, out processId);
            if (processId != 0)
            {
                Process process = Process.GetProcessById((int)processId);
                process.Kill();
            }
        }

        public static void CloseActiveWindowAndKillProcess()
        {
            IntPtr foregroundWindow = GetForegroundWindowHandle();
            if (foregroundWindow != IntPtr.Zero)
            {
                CloseActiveWindow(); // Close the window
                KillProcessAssociatedWithWindow(foregroundWindow); // Kill the related process
            }
        }
    }
```
    
In
    https://github.com/darklinkpower/PlayniteExtensionsCollection/blob/master/source/Generic/PlayState/WindowsHelper.cs

**Comment by andrew-codes** [comment]
This is perfect!

**Comment by andrew-codes** [comment]
I have a PR ready, just need to verify it in my test environment prior to releasing.
