### ISSUE TITLE
Missing releaseId in game state message of Playnite plugin

### ISSUE THREAD

**Issue by cvele** [andrew-codes/playnite-web#580]
When determining the game state, the plugin currently publishes a message that includes processId, gameId, and status. However, the releaseId is missing and should be included to accurately identify which specific release is running.

**Comment by andrew-codes** [comment]
Thanks for the report. I have an incoming fix. I'm also going to document the mqtt messages soon, tracked by another issue.

**Comment by andrew-codes** [comment]
Just wanted to let you know the fix is incoming. ![image](https://github.com/user-attachments/assets/dcdde669-9bf6-48d9-90f5-a950d723e7ba)
