### ISSUE TITLE
Installer manifest has wrong SDK dependency version set

### ISSUE THREAD

**Issue by JosefNemec** [andrew-codes/playnite-web#623]
https://raw.githubusercontent.com/andrew-codes/playnite-web/refs/heads/main/apps/PlayniteWebPlugin/src/manifest.yaml

You are referencing `6.11` in the project but manifest specifies `5.6.0`, which makes it impossible to be installed via addon browser in Playnite itself, because 5.x SDK is only compatible with old Playnite 9.

**Comment by andrew-codes** [comment]
Thank you! I wasn't completely certain what value to use. This is good to know and I'll update today. Thank you again!

**Comment by JosefNemec** [comment]
It should be a version of Playnite SDK nuget your plugin references.

**Comment by andrew-codes** [comment]
> It should be a version of Playnite SDK nuget your plugin references.

Ah ok, that makes sense. Thans for the clarification.
